// Code generated by Kitex v0.4.4. DO NOT EDIT.

package videoservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	videoservice "github.com/gdan0324/ByteWeGo/video/kitex_gen/videoservice"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateVideo(ctx context.Context, req *videoservice.CreateVideoRequest, callOptions ...callopt.Option) (r *videoservice.CreateVideoResponse, err error)
	GetVideoList(ctx context.Context, req *videoservice.GetVideoListRequest, callOptions ...callopt.Option) (r *videoservice.GetVideoListResponse, err error)
	GetFeed(ctx context.Context, req *videoservice.GetFeedRequest, callOptions ...callopt.Option) (r *videoservice.GetFeedResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kVideoServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kVideoServiceClient struct {
	*kClient
}

func (p *kVideoServiceClient) CreateVideo(ctx context.Context, req *videoservice.CreateVideoRequest, callOptions ...callopt.Option) (r *videoservice.CreateVideoResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateVideo(ctx, req)
}

func (p *kVideoServiceClient) GetVideoList(ctx context.Context, req *videoservice.GetVideoListRequest, callOptions ...callopt.Option) (r *videoservice.GetVideoListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetVideoList(ctx, req)
}

func (p *kVideoServiceClient) GetFeed(ctx context.Context, req *videoservice.GetFeedRequest, callOptions ...callopt.Option) (r *videoservice.GetFeedResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFeed(ctx, req)
}
