// Code generated by Kitex v0.4.4. DO NOT EDIT.
package userservice

import (
	server "github.com/cloudwego/kitex/server"
	userservice "github.com/gdan0324/ByteWeGo/api/kitex_gen/userservice"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler userservice.UserService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
