// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	handler "github.com/gdan0324/ByteWeGo/api/biz/handler"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	// your code ...

	r.POST("/douyin/relation/action", handler.Follow)

	r.GET("/douyin/relation/follow/list", handler.FollowList)

	r.GET("/douyin/relation/follower/list", handler.FollowerList)

	r.GET("/douyin/relation/friend/list", handler.CheckFriend)

	r.POST("/douyin/message/action", handler.MessageAction)
}
