// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	handler "github.com/gdan0324/ByteWeGo/api/biz/handler"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	// your code ...
	//r.POST("/user", handler.CheckUser)

	r.POST("/douyin/comment/action/", handler.CommentAction)
	r.GET("/douyin/comment/list/", handler.GetComments)
}
