// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	handler "github.com/gdan0324/ByteWeGo/api/biz/handler"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	// user routes
	r.POST("/douyin/user/login", handler.CheckUser)
	r.POST("/douyin/user/register", handler.CreateUser)
	r.GET("/douyin/user", handler.GetUser)
}
